stages:
  - build
  - test
gcc7_lcg95:build:
  stage: build

  image: gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest
  variables:
    CMTCONFIG: x86_64-centos7-gcc7-opt
    LCG: LCG_95
  script:
    - "#!/usr/bin/env bash"
    - "./scripts/bootstrap ${LCG}  ${CMTCONFIG}" 
  artifacts:
    paths:
      - build
gcc7_lcg95:test:
  stage: test
  variables:
    CMTCONFIG: x86_64-centos7-gcc7-opt
    LCG: LCG_95
  script:
    - "#!/usr/bin/env bash"
    - "./scripts/test ${LCG}  ${CMTCONFIG}"
  needs:
    - job: gcc7_lcg95:build
      artifacts: true
  artifacts:
    paths:
      - build
    when: on_failure
