stages:
  - build
#  - test

variables:
  CMTCONFIG: x86_64-slc6-gcc62-dbg

local-build:
  image: gitlab-registry.cern.ch/lhcb-core/lbdocker/slc6-build:latest
  tags:
    - cvmfs
  stage: build
  script:
    - . /cvmfs/lhcb.cern.ch/lib/group_login.sh
    - source /cvmfs/sft.cern.ch/lcg/views/LCG_95/${CMTCONFIG}/setup.sh
    - mkdir build 
    - cd build 
    - cmake .. -DCMAKE_INSTALL_PREFIX=./INSTALL/
    - make
    - make install
    - cd .. 
