stages:
  - build
  - test
image: gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest
gcc7_lcg95:build:
  stage: build
  variables:
    CMTCONFIG: x86_64-centos7-gcc7-opt
    LCG: LCG_95
  script:
    - "#!/usr/bin/env bash"
    - "./scripts/bootstrap ${LCG}  ${CMTCONFIG}" 
    - "cd .."
gcc7_lcg95:test:
  stage: test
  variables:
    CMTCONFIG: x86_64-centos7-gcc7-opt
    LCG: LCG_95
  script:
    - "#!/usr/bin/env bash"
    - "ls ."
    - "./scripts/test ${LCG}  ${CMTCONFIG}"
    - "cd .."

