stages:
  - build
#  - test

variables:
  CMTCONFIG: x86_64-slc6-gcc62-opt

local-build:
  image: gitlab-registry.cern.ch/lhcb-core/lbdocker/slc6-build:latest
  tags:
    - cvmfs
  stage: build
  script:
    - echo "build will be here"
