sudo: required
services:
  - docker

before_install:
  - docker pull gitlab-registry.cern.ch/lhcb-core/lbdocker/slc6-build:latest


script: 
 - docker run -v /cvmfs:/cvmfs -v ${PWD}:/ostap  --privileged=true  gitlab-registry.cern.ch/lhcb-core/lbdocker/slc6-build:latest   /bin/bash -c "cp -r ../ostap . && cd ostap && ./scripts/bootstrap"