# File: azure-pipelines.yml

jobs:
- template: template-pipelines.yml  # Template reference
  parameters:
    name: sl6_lcg95
    vmImage: 'ubuntu-16.04'
    dockername: 'gitlab-registry.cern.ch/lhcb-core/lbdocker/slc6-build:latest'
    LCG: 'LCG_95'
    artifact: 'test_sl6_lcg95'
- template: template-pipelines.yml  # Template reference
  parameters:
    name: centos7_lcg_95
    vmImage:  'ubuntu-16.04'
    dockername: 'gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest'
    LCG: 'LCG_95'
    artifact: 'test_cs7_lcg95'
