# File: azure-pipelines.yml
jobs:
- template: template-pipelines.yml  # Template reference
  parameters:
    name: cs7_lcg_95_gcc8_python2
    vmImage:  'ubuntu-16.04'
    dockername: 'gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest'
    LCG: 'LCG_95'
    CMTCONFIG: 'x86_64-centos7-gcc8-opt'
    artifact: 'test_cs7_lcg95_gcc8_python2'
- template: template-pipelines.yml  # Template reference
  parameters:
    name: cs7_lcg_96_gcc8_python2
    vmImage:  'ubuntu-16.04'
    dockername: 'gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest'
    LCG: 'LCG_96'
    CMTCONFIG: 'x86_64-centos7-gcc8-opt'
    artifact: 'test_cs7_lcg96_gcc8_python2'
- template: template-pipelines.yml  # Template reference
  parameters:
    name: cs7_lcg_96_gcc8_python3
    vmImage:  'ubuntu-16.04'
    dockername: 'gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest'
    LCG: 'LCG_96python3'
    CMTCONFIG: 'x86_64-centos7-gcc8-opt'
    artifact: 'test_cs7_lcg96_gcc8_python3'
